version: '3'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
    depends_on:
      - database
#    environment:
#      - APP_ENV=${APP_ENV}
#      - APP_SECRET=${APP_SECRET}
#      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src/:/var/www
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./src/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 58276:5432
    volumes:
      - ./docker/database:/var/lib/postgresql/data